name: CI - Build the project

on: 
  push: 
    branches: [ develop ] 
  pull_request:
    branches: [ develop ]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with: 
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Build the project
        run: yarn build
      
